sudo: false
language: node_js
node_js:
  - "4.2.3"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
rvm:
  - 2.1.7
cache:
  directories:
    - node_modules
before_install:
  - npm install -g grunt-cli
  - gem update --system && gem install scss_lint -v 0.43.2
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
