sudo: false
language: node_js
node_js:
  - "0.12.5"
rvm:
  - 2.1.7
cache:
  directories:
    - node_modules
before_install:
  - npm install -g grunt-cli
  - gem update --system && gem install scss-lint -v 0.34.0
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
